10

diff --git a/sijhon b/sijhon
--- a/sijhon
+++ b/sijhon
@@ -1,3 +1,136 @@
-z="
-";Cz='\e[0';AGz='-r l';gz='ta/n';LGz='rm a';JDz='⣤⣀⠀⠀';PFz=':$m ';KBz='in';vBz='e)';bz=' -e ';BGz='ine;';XDz='i   ';fGz='e ht';yCz='e" ]';xCz='f "$';HBz='OME/';xDz='⡟ $b';kGz='/sij';yDz=' tah';NGz='$h';MCz='stat';aCz='rmux';kCz='1';RGz='S"';sGz='/log';Dz=';30m';ZCz='m.te';MFz='nona';WDz=' har';qz='n';Oz='36;1';Xz='ta';Sz='33;1';IEz='tus ';mBz='n=$(';yz='f da';pBz=' +%Y';lFz='4513';OCz='(who';tz='n/$(';qGz='0.sh';FEz='⡿⠷⠀⣿';Ez=''\''';Hz='30;0';bDz='⣀⭕⠀⠀';jDz='al';vFz='whil';wCz=' ! -';MBz='rf d';EBz='bin';jFz='0760';DGz=' "$l';ZDz='i';GGz=' < "';vEz='IN :';iz='"$(d';aFz='"www';kz='+%Y-';VBz='~~~~';PCz='ami)';kBz='%d)';oFz='bash';ACz='bin/';GCz='$HOM';iEz='ect ';bGz='NDCO';KCz='/idd';jz='ate ';CCz='/nam';NFz='ktif';ODz=' jam';FCz='(ls ';hGz='//gi';NBz='rf s';Gz='033[';RDz='$jam';IBz='../u';FBz='f id';yEz='ng"';oDz='⣿ $b';VDz='⠻⣿⣿⣇';lz='%m-%';WBz='~"';GBz='d $H';eEz='Z$h';EFz='"$a	';eDz='⣿⣿⣆ ';JCz='/bin';eCz='oads';ZBz='----';BFz='}$ga';XEz='⢿⣿⣿⣿';FDz='  ⠛⠛';XGz='alia';yFz='ead ';gEz='"$p ';nEz='$ip"';fz='> da';TDz='⠻⣿⣿⠿';kDz='⠀⠹⠏⠀';tEz='h"';rDz='$bul';CGz=' do';hBz='+%A)';iCz='slee';CDz='$m';Az='txtb';gBz='=$(d';KEz='tus';lCz='h ak';wEz='$k l';GDz='⣿⣿⣿⣿';dGz='git ';sCz='1729';qEz='   :';LDz=' ⠀⠀⠀';JFz='"$a ';PEz='tem ';ADz='; th';pz='d/jo';mEz='k | ';BDz='en';TBz='gari';OEz=' sys';gDz='angg';JGz='me" ';pEz='	 ID';MDz='⣿⣿⣷⡀';BBz='HOME';mFz='$a';Mz='31;1';Pz='p='\''\';Iz='m'\''';hFz='p?id';Lz='m='\''\';MGz='ku';cz='"$(w';lEz='me $';SCz='(una';pCz='e=($';xEz='oadi';rFz='h';jGz='.com';WEz='⠀⠀⠙⠻';tBz='conf';oCz='_nam';fBz='hari';ECz='id=$';nCz='file';eFz='m/pr';mCz='u';rGz='ME/l';ZEz='a AU';sDz='an';nDz='⣿⣿⣿⡿';cCz='es/u';YFz='ACT ';TEz='⣿⣿⣿⠀';FGz='done';TCz='me)';wFz='e IF';aBz='---"';wBz='name';EDz='${m}';dBz='te +';dEz='ton ';gGz='tps:';cDz='⢸⣷ ⭕';KGz='> ak';PGz='$h S';Bz='lk='\''';oEz='"$p	';FFz='	LOG';NEz='⣤⣶⣦⠃';QFz='$(ls';UEz='⠈⣿⣿⣿';sEz='id $';Zz='d';Qz='1;35';hDz='al:$';VFz='n/id';oBz='tahu';UBz='s="~';SBz='r';wDz='⣿⠛⢯⡿';DFz='p 3';YDz='$har';fCz='Mtk ';kEz=' $na';oGz='cp l';REz='tem';VGz='xtbl';LCz='/jon';bBz='jam=';nz='ta/d';KFz='KEY ';VEz='⣿⣿⡇⠀';bEz=': Pl';QGz='UCCE';DCz='a)';sBz='l if';ZFz='Z$h"';Vz='mkdi';dCz='in/l';fFz='ofil';QDz=':$h ';Tz='b='\''\';vDz='⠇⢀⣼⣿';UFz='r/bi';VCz='="0"';nBz=' +%m';mGz='/ssh';Fz='a='\''\';CEz='un';RCz='em=$';xBz='=$(c';iGz='thub';iBz='tang';lBz='bula';uGz='.';cGz='LOR}';SFz='ME/.';mz='d)" ';YGz='n it';SEz='⢐⣿⣾⣿';gFz='e.ph';nFz='p 5';CFz='ris"';ZGz='alic';sFz='exit';rz='touc';HEz=' sta';hz='ama';eGz='clon';uBz='ig.m';hCz='n.sh';yBz='at $';QCz='syst';bCz='/fil';RFz=' $HO';WGz='k}It';qFz='in.s';BEz='$tah';dDz='⣀⣤⣴⣿';eBz='%T)';rEz='$k $';QEz='$sys';WFz='n)"';wz=')';UDz='⠿⠛⠛⠛';lDz='⠀⠀⣿⣧';ez='i)" ';Nz='c='\''\';GEz='⠀ $p';pDz=' bul';uDz='⠀⠀⠛⠿';bFz='.fac';XCz='/dat';dFz='k.co';qBz='ip=$';fEz='p 2';mDz='⠀⠹⣿⣿';OFz='ID  ';Uz='34;m';KDz='⠀';YEz='⣿⠟⠁$';CBz='/../';qCz='idd/';cBz='$(da';dz='hoam';uEz='	 CO';oz='ata';Yz='r id';uFz='fi';SDz='⠉⠉⠉⠙';pGz='ogin';UCz='coin';cEz='anks';DBz='usr/';qDz='an  ';YBz='h="-';PDz='    ';az='echo';LFz=':$k ';SGz='akti';jCz='p 0.';Kz='32;1';IFz='D"';RBz='clea';IDz='⣶⣶⣤⣤';AFz='"${a';aEz='THOR';IGz='e_na';tGz='cd .';xz='mv -';TFz='./us';Wz='r da';BCz='data';NCz='us=$';rBz='(cur';DDz='"';vz=' +%s';ABz='ta $';HFz='AILE';NDz='⠀ $b';sz='h id';xFz='S= r';pFz=' log';nGz='cd s';TGz='f$a"';JEz='$sta';vCz='if [';Rz='k='\''\';iDz='h $t';LEz='⠙⣷⣶⣶';EEz='⠴⢿⢿⣿';hEz='cunn';QBz='dd';ICz='/usr';UGz='"${t';EGz='ine"';Jz='h='\''\';HGz='$fil';YCz='a/co';aDz='⠀⢤⣀⣀';PBz='rf i';uz='date';iFz='=100';HCz='E/..';rCz='jon/';uCz='34)';OGz='${h}';tFz=' 1';WCz='cp /';GFz='$m F';tCz='4383';kFz='6203';AEz='un  ';jBz='gal=';jEz='as$a';DEz='⠀⠀⠀⠦';MEz='⣤⣤⣤⣤';LBz='rm -';HDz='⣿⡷⢶⣦';lGz='hons';XBz='pisa';cFz='eboo';JBz='sr/b';tDz='⠀⠀⠀⠀';OBz='sh';fDz='$b t';aGz='s${E';XFz='CONT';gCz='logi';
-eval "$Az$Bz$Cz$Dz$Ez$z$Fz$Gz$Hz$Iz$z$Jz$Gz$Kz$Iz$z$Lz$Gz$Mz$Iz$z$Nz$Gz$Oz$Iz$z$Pz$Gz$Qz$Iz$z$Rz$Gz$Sz$Iz$z$Tz$Gz$Uz$Ez$z$Vz$Wz$Xz$z$Vz$Yz$Zz$z$az$bz$cz$dz$ez$fz$gz$hz$z$az$bz$iz$jz$kz$lz$mz$fz$nz$oz$z$Vz$Yz$pz$qz$z$rz$sz$pz$tz$uz$vz$wz$z$xz$yz$ABz$BBz$CBz$DBz$EBz$z$xz$FBz$GBz$HBz$IBz$JBz$KBz$z$LBz$MBz$oz$z$LBz$NBz$OBz$z$LBz$PBz$QBz$z$RBz$SBz$z$TBz$UBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$VBz$WBz$z$XBz$YBz$ZBz$ZBz$ZBz$ZBz$ZBz$ZBz$ZBz$ZBz$ZBz$ZBz$ZBz$aBz$z$bBz$cBz$dBz$eBz$z$fBz$gBz$jz$hBz$z$iBz$jBz$cBz$dBz$kBz$z$lBz$mBz$uz$nBz$wz$z$oBz$mBz$uz$pBz$wz$z$qBz$rBz$sBz$tBz$uBz$vBz$z$wBz$xBz$yBz$BBz$CBz$DBz$ACz$BCz$CCz$DCz$z$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$wz$z$MCz$NCz$OCz$PCz$z$QCz$RCz$SCz$TCz$z$UCz$VCz$z$RBz$SBz$z$WCz$BCz$XCz$YCz$ZCz$aCz$bCz$cCz$JBz$dCz$eCz$fCz$gCz$hCz$z$iCz$jCz$kCz$z$RBz$SBz$z$rz$lCz$mCz$z$nCz$oCz$pCz$BBz$CBz$DBz$ACz$qCz$rCz$sCz$tCz$uCz$z$vCz$wCz$xCz$nCz$oCz$yCz$ADz$BDz$z$iCz$jCz$kCz$z$az$bz$CDz$z$iCz$jCz$kCz$z$az$bz$DDz$z$EDz$FDz$GDz$HDz$IDz$JDz$KDz$z$EDz$LDz$GDz$GDz$GDz$MDz$NDz$ODz$PDz$QDz$RDz$z$EDz$LDz$SDz$TDz$UDz$VDz$NDz$WDz$XDz$QDz$YDz$ZDz$z$EDz$aDz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$gDz$jDz$z$EDz$LDz$kDz$lDz$mDz$nDz$oDz$pDz$qDz$QDz$rDz$sDz$z$EDz$LDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$QDz$BEz$CEz$z$EDz$LDz$tDz$DEz$EEz$FEz$GEz$HEz$IEz$QDz$JEz$KEz$z$EDz$LDz$tDz$LEz$MEz$NEz$GEz$OEz$PEz$QDz$QEz$REz$z$EDz$LDz$tDz$SEz$GDz$TEz$KDz$z$EDz$LDz$tDz$UEz$GDz$VEz$KDz$z$EDz$LDz$tDz$WEz$XEz$YEz$ZEz$aEz$bEz$cEz$dEz$eEz$z$DDz$z$iCz$fEz$z$az$bz$gEz$PDz$hEz$iEz$jEz$kEz$lEz$mEz$nEz$z$iCz$jCz$kCz$z$az$bz$oEz$pEz$qEz$rEz$sEz$tEz$z$iCz$jCz$kCz$z$az$bz$oEz$uEz$vEz$wEz$xEz$yEz$z$iCz$jCz$kCz$z$az$bz$AFz$BFz$CFz$z$iCz$DFz$z$az$bz$EFz$FFz$vEz$GFz$HFz$IFz$z$iCz$jCz$kCz$z$az$bz$AFz$BFz$CFz$z$az$bz$JFz$KFz$PDz$LFz$MFz$NFz$DDz$z$az$bz$JFz$OFz$PDz$PFz$QFz$RFz$SFz$TFz$UFz$VFz$pz$WFz$z$az$bz$JFz$XFz$YFz$bEz$cEz$dEz$ZFz$z$az$bz$aFz$bFz$cFz$dFz$eFz$fFz$gFz$hFz$iFz$jFz$kFz$lFz$DDz$z$az$bz$mFz$z$iCz$nFz$z$oFz$pFz$qFz$rFz$z$sFz$tFz$z$uFz$z$vFz$wFz$xFz$yFz$AGz$BGz$CGz$z$az$DGz$EGz$z$FGz$GGz$HGz$IGz$JGz$KGz$mCz$z$LGz$MGz$z$iCz$jCz$kCz$z$az$bz$NGz$z$iCz$jCz$kCz$z$az$bz$DDz$z$OGz$FDz$GDz$HDz$IDz$JDz$KDz$z$OGz$LDz$GDz$GDz$GDz$MDz$NDz$ODz$PDz$QDz$RDz$z$OGz$LDz$SDz$TDz$UDz$VDz$NDz$WDz$XDz$QDz$YDz$ZDz$z$OGz$aDz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$gDz$jDz$z$OGz$LDz$kDz$lDz$mDz$nDz$oDz$pDz$qDz$QDz$rDz$sDz$z$OGz$LDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$QDz$BEz$CEz$z$OGz$LDz$tDz$DEz$EEz$FEz$GEz$HEz$IEz$QDz$JEz$KEz$z$OGz$LDz$tDz$LEz$MEz$NEz$GEz$OEz$PEz$QDz$QEz$REz$z$OGz$LDz$tDz$SEz$GDz$TEz$KDz$z$OGz$LDz$tDz$UEz$GDz$VEz$KDz$z$OGz$LDz$tDz$WEz$XEz$YEz$ZEz$aEz$bEz$cEz$dEz$eEz$z$DDz$z$iCz$fEz$z$az$bz$gEz$PDz$hEz$iEz$jEz$kEz$lEz$mEz$nEz$z$iCz$jCz$kCz$z$az$bz$oEz$pEz$qEz$rEz$sEz$tEz$z$iCz$jCz$kCz$z$az$bz$oEz$uEz$vEz$wEz$xEz$yEz$z$iCz$jCz$kCz$z$az$bz$AFz$BFz$CFz$z$iCz$DFz$z$az$bz$EFz$FFz$vEz$PGz$QGz$RGz$z$iCz$jCz$kCz$z$az$bz$JFz$KFz$PDz$QDz$SGz$TGz$z$az$bz$JFz$OFz$PDz$QDz$QFz$RFz$SFz$TFz$UFz$VFz$pz$WFz$z$az$bz$JFz$XFz$YFz$bEz$cEz$dEz$ZFz$z$az$bz$aFz$bFz$cFz$dFz$eFz$fFz$gFz$hFz$iFz$jFz$kFz$lFz$DDz$z$az$bz$mFz$z$iCz$nFz$z$az$bz$UGz$VGz$WGz$XGz$YGz$ZGz$aGz$bGz$cGz$DDz$z$dGz$eGz$fGz$gGz$hGz$iGz$jGz$kGz$lGz$mGz$z$nGz$OBz$z$oGz$pGz$qGz$RFz$rGz$pGz$sGz$qFz$rFz$z$tGz$uGz$z$WCz$BCz$XCz$YCz$ZCz$aCz$bCz$cCz$JBz$dCz$eCz$fCz$gCz$hCz"
+#!/bin/bash
+
+#color
+txtblk='\e[0;30m'
+a='\033[30;0m'
+h='\033[32;1m'
+m='\033[31;1m'
+c='\033[36;1m'
+p='\033[1;35m'
+k='\033[33;1m'
+b='\033[34;m'
+
+#variable
+mkdir data
+mkdir idd
+echo -e "$(whoami)" > data/nama
+echo -e "$(date +%Y-%m-%d)" > data/data
+mkdir idd/jon
+touch idd/jon/$(date +%s)
+mv -f data $HOME/../usr/bin
+mv -f idd $HOME/../usr/bin
+rm -rf data
+rm -rf ssh
+rm -rf idd
+clear
+garis="~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+pisah="------------------------------------------------"
+jam=$(date +%T)
+hari=$(date +%A)
+tanggal=$(date +%d)
+bulan=$(date +%m)
+tahun=$(date +%Y)
+ip=$(curl ifconfig.me)
+name=$(cat $HOME/../usr/bin/data/nama)
+id=$(ls $HOME/../usr/bin/idd/jon)
+status=$(whoami)
+system=$(uname)
+coin="0"
+clear
+
+cp /data/data/com.termux/files/usr/bin/loadsMtk login.sh
+sleep 0.1
+
+clear
+#menu
+touch aku
+file_name=($HOME/../usr/bin/idd/jon/1729438334)
+#read -p "file: " file_name
+
+# Check if the file exists
+if [ ! -f "$file_name" ]; then
+  sleep 0.1
+  echo -e $m
+  sleep 0.1
+  echo -e "
+${m}  ⠛⠛⣿⣿⣿⣿⣿⡷⢶⣦⣶⣶⣤⣤⣤⣀⠀⠀⠀
+${m} ⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀ $b jam    :$h $jam
+${m} ⠀⠀⠀⠉⠉⠉⠙⠻⣿⣿⠿⠿⠛⠛⠛⠻⣿⣿⣇⠀ $b hari   :$h $hari
+${m}⠀⢤⣀⣀⣀⭕⠀⠀⢸⣷ ⭕⣀⣤⣴⣿⣿⣿⣆ $b tanggal:$h $tanggal
+${m} ⠀⠀⠀⠀⠹⠏⠀⠀⠀⣿⣧⠀⠹⣿⣿⣿⣿⣿⡿⣿ $b bulan  :$h $bulan
+${m} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠿⠇⢀⣼⣿⣿⠛⢯⡿⡟ $b tahun  :$h $tahun
+${m} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠦⠴⢿⢿⣿⡿⠷⠀⣿⠀ $p status :$h $status
+${m} ⠀⠀⠀⠀⠀⠀⠀⠙⣷⣶⣶⣤⣤⣤⣤⣤⣶⣦⠃⠀ $p system :$h $system
+${m} ⠀⠀⠀⠀⠀⠀⠀⢐⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀
+${m} ⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀
+${m} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⠟⠁$a AUTHOR: Plankston Z$h
+"
+  sleep 2
+  echo -e "$p     cunnect as$a $name $k | $ip"
+  sleep 0.1
+  echo -e "$p		 ID   :$k $id $h"
+  sleep 0.1
+  echo -e "$p		 COIN :$k loading"
+  sleep 0.1
+  echo -e "${a}$garis"
+  sleep 3
+  echo -e "$a		LOGIN :$m FAILED"
+  sleep 0.1
+  echo -e "${a}$garis"
+  echo -e "$a KEY     :$k nonaktif"
+  echo -e "$a ID      :$m $(ls $HOME/../usr/bin/idd/jon)"
+  echo -e "$a CONTACT : Plankston Z$h"
+  echo -e "www.facebook.com/profile.php?id=100076062034513"
+  echo -e $a
+  sleep 5
+  bash login.sh
+  exit 1
+fi
+
+# Read the file line by line
+while IFS= read -r line; do
+  # Process each line here
+  # For example, print the line to the console:
+  echo "$line"
+done < "$file_name" > aku
+rm aku
+sleep 0.1
+  echo -e $h
+  sleep 0.1
+  echo -e "
+${h}  ⠛⠛⣿⣿⣿⣿⣿⡷⢶⣦⣶⣶⣤⣤⣤⣀⠀⠀⠀
+${h} ⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀ $b jam    :$h $jam
+${h} ⠀⠀⠀⠉⠉⠉⠙⠻⣿⣿⠿⠿⠛⠛⠛⠻⣿⣿⣇⠀ $b hari   :$h $hari
+${h}⠀⢤⣀⣀⣀⭕⠀⠀⢸⣷ ⭕⣀⣤⣴⣿⣿⣿⣆ $b tanggal:$h $tanggal
+${h} ⠀⠀⠀⠀⠹⠏⠀⠀⠀⣿⣧⠀⠹⣿⣿⣿⣿⣿⡿⣿ $b bulan  :$h $bulan
+${h} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠿⠇⢀⣼⣿⣿⠛⢯⡿⡟ $b tahun  :$h $tahun
+${h} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠦⠴⢿⢿⣿⡿⠷⠀⣿⠀ $p status :$h $status
+${h} ⠀⠀⠀⠀⠀⠀⠀⠙⣷⣶⣶⣤⣤⣤⣤⣤⣶⣦⠃⠀ $p system :$h $system
+${h} ⠀⠀⠀⠀⠀⠀⠀⢐⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀
+${h} ⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀
+${h} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⠟⠁$a AUTHOR: Plankston Z$h
+"
+  sleep 2
+  echo -e "$p     cunnect as$a $name $k | $ip"
+  sleep 0.1
+  echo -e "$p		 ID   :$k $id $h"
+  sleep 0.1
+  echo -e "$p		 COIN :$k loading"
+  sleep 0.1
+  echo -e "${a}$garis"
+  sleep 3
+  echo -e "$a		LOGIN :$h SUCCES"
+  sleep 0.1
+echo -e "$a KEY     :$h aktif$a"
+echo -e "$a ID      :$h $(ls $HOME/../usr/bin/idd/jon)"
+echo -e "$a CONTACT : Plankston Z$h"
+echo -e "www.facebook.com/profile.php?id=100076062034513"
+echo -e $a
+sleep 5
+echo -e "${txtblk}Italian italics${ENDCOLOR}"
+git clone https://github.com/sijhons/ssh
+cd ssh
+cp login0.sh $HOME/login/login.sh
+cd ..
+cp /data/data/com.termux/files/usr/bin/loadsMtk login.sh
+
